# **NOTEBOOK 2: ALIE RECOMMENDATION ENGINE**

# **PHASE 1: SYNTHESIZING FEATURES**

**1. REFERENCE CREATION**

In [113]:
import pandas as pd
import numpy as np
import random
import os
!pip install faker
import faker
from faker import Faker
from datetime import datetime, timedelta
import string

Requirement already satisfied: faker in /usr/local/lib/python3.12/dist-packages (40.36.0)

In [114]:
SEED = 42
np.random.seed(SEED)
random.seed(SEED)

try:
    from faker import Faker

    fake = Faker()
    Faker.seed(SEED)
    USE_FAKER = True
except ImportError:
    USE_FAKER = False

_FIRST_NAMES = [
    "Aarav", "Vivaan", "Aditya", "Vihaan", "Arjun", "Sai", "Reyansh", "Ayaan",
    "Krishna", "Ishaan", "Rohan", "Kabir", "Aryan", "Dev", "Yash", "Kunal",
    "Ananya", "Diya", "Saanvi", "Aadhya", "Myra", "Ira", "Anika", "Navya",
    "Kiara", "Riya", "Sara", "Pari", "Meera", "Tara", "Priya", "Neha",
    "James", "Liam", "Noah", "Oliver", "Ethan", "Lucas", "Mason", "Logan",
    "Emma", "Olivia", "Ava", "Sophia", "Isabella", "Mia", "Chloe", "Grace",
    "Wei", "Jun", "Hiro", "Yuki", "Min-jun", "Sofia", "Lucia", "Mateo",
    "Fatima", "Ahmed", "Omar", "Zainab", "Layla", "Yusuf", "Hassan", "Amir",
]
_LAST_NAMES = [
    "Sharma", "Verma", "Gupta", "Iyer", "Nair", "Reddy", "Rao", "Mehta",
    "Kapoor", "Malhotra", "Chatterjee", "Bose", "Patel", "Shah", "Joshi",
    "Kulkarni", "Pillai", "Menon", "Singh", "Yadav", "Das", "Mishra",
    "Smith", "Johnson", "Brown", "Williams", "Jones", "Garcia", "Martinez",
    "Kim", "Chen", "Wang", "Tanaka", "Suzuki", "Khan", "Ali", "Hussain",
]


def generate_name():
    """Return a plausible full name, using Faker if available."""
    if USE_FAKER:
        return fake.name()
    return f"{random.choice(_FIRST_NAMES)} {random.choice(_LAST_NAMES)}"


def slugify(text):
    keep = string.ascii_letters + string.digits + " "
    cleaned = "".join(c for c in text if c in keep)
    return cleaned.strip().lower().replace(" ", "-")


OUTPUT_DIR = "lms_dataset"
os.makedirs(OUTPUT_DIR, exist_ok=True)
np.random.seed(SEED)
random.seed(SEED)
Faker.seed(SEED)

fake = Faker()

In [115]:

CURRICULUM = [

    {"education_level": "Grade 6-12", "course": "Grade 6", "stream": None,
     "term_type": "grade", "num_terms": 1, "age_range": (11, 12),
     "subjects": ["Mathematics", "Science", "English", "Social Science", "Hindi"]},
    {"education_level": "Grade 6-12", "course": "Grade 7", "stream": None,
     "term_type": "grade", "num_terms": 1, "age_range": (12, 13),
     "subjects": ["Mathematics", "Science", "English", "Social Science", "Hindi"]},
    {"education_level": "Grade 6-12", "course": "Grade 8", "stream": None,
     "term_type": "grade", "num_terms": 1, "age_range": (13, 14),
     "subjects": ["Mathematics", "Science", "English", "Social Science", "Hindi"]},
    {"education_level": "Grade 6-12", "course": "Grade 9", "stream": None,
     "term_type": "grade", "num_terms": 1, "age_range": (14, 15),
     "subjects": ["Mathematics", "Science", "English", "Social Science", "Computer Basics"]},
    {"education_level": "Grade 6-12", "course": "Grade 10", "stream": None,
     "term_type": "grade", "num_terms": 1, "age_range": (15, 16),
     "subjects": ["Mathematics", "Science", "English", "Social Science", "Computer Basics"]},
    {"education_level": "Grade 6-12", "course": "Grade 11", "stream": "Science",
     "term_type": "grade", "num_terms": 1, "age_range": (16, 17),
     "subjects": ["Physics", "Chemistry", "Mathematics", "Biology", "English"]},
    {"education_level": "Grade 6-12", "course": "Grade 11", "stream": "Commerce",
     "term_type": "grade", "num_terms": 1, "age_range": (16, 17),
     "subjects": ["Accountancy", "Business Studies", "Economics", "Mathematics", "English"]},
    {"education_level": "Grade 6-12", "course": "Grade 11", "stream": "Arts",
     "term_type": "grade", "num_terms": 1, "age_range": (16, 17),
     "subjects": ["History", "Political Science", "Geography", "Sociology", "English"]},
    {"education_level": "Grade 6-12", "course": "Grade 12", "stream": "Science",
     "term_type": "grade", "num_terms": 1, "age_range": (17, 18),
     "subjects": ["Physics", "Chemistry", "Mathematics", "Biology", "English"]},
    {"education_level": "Grade 6-12", "course": "Grade 12", "stream": "Commerce",
     "term_type": "grade", "num_terms": 1, "age_range": (17, 18),
     "subjects": ["Accountancy", "Business Studies", "Economics", "Mathematics", "English"]},
    {"education_level": "Grade 6-12", "course": "Grade 12", "stream": "Arts",
     "term_type": "grade", "num_terms": 1, "age_range": (17, 18),
     "subjects": ["History", "Political Science", "Geography", "Sociology", "English"]},


    {"education_level": "Diploma", "course": "Diploma in Computer Science", "stream": "Computer Science",
     "term_type": "semester", "num_terms": 6, "age_range": (15, 19),
     "subjects": ["Programming Fundamentals", "Data Structures", "DBMS",
                  "Web Development", "Computer Networks", "Operating Systems"]},
    {"education_level": "Diploma", "course": "Diploma in Mechanical Engineering", "stream": "Mechanical",
     "term_type": "semester", "num_terms": 6, "age_range": (15, 19),
     "subjects": ["Engineering Mechanics", "Thermodynamics", "Machine Design",
                  "Manufacturing Processes", "Strength of Materials", "Fluid Mechanics"]},
    {"education_level": "Diploma", "course": "Diploma in Civil Engineering", "stream": "Civil",
     "term_type": "semester", "num_terms": 6, "age_range": (15, 19),
     "subjects": ["Surveying", "Structural Analysis", "Building Materials",
                  "Concrete Technology", "Geotechnical Engineering", "Transportation Engineering"]},
    {"education_level": "Diploma", "course": "Diploma in Electronics Engineering", "stream": "Electronics",
     "term_type": "semester", "num_terms": 6, "age_range": (15, 19),
     "subjects": ["Circuit Theory", "Digital Electronics", "Microprocessors",
                  "Communication Systems", "Electronic Devices", "Control Systems"]},


    {"education_level": "Undergraduate", "course": "BTech Computer Science", "stream": "Computer Science",
     "term_type": "semester", "num_terms": 8, "age_range": (18, 23),
     "subjects": ["OOP", "DBMS", "Operating Systems", "Computer Networks",
                  "Data Structures", "Algorithms", "Software Engineering", "Web Technologies"]},
    {"education_level": "Undergraduate", "course": "BTech Artificial Intelligence", "stream": "Artificial Intelligence",
     "term_type": "semester", "num_terms": 8, "age_range": (18, 23),
     "subjects": ["Machine Learning", "Deep Learning", "Statistics", "OOP", "DBMS",
                  "Natural Language Processing", "Computer Vision", "Reinforcement Learning"]},
    {"education_level": "Undergraduate", "course": "BTech Mechanical Engineering", "stream": "Mechanical",
     "term_type": "semester", "num_terms": 8, "age_range": (18, 23),
     "subjects": ["Thermodynamics", "Fluid Mechanics", "Machine Design",
                  "Manufacturing Processes", "Strength of Materials", "Heat Transfer"]},
    {"education_level": "Undergraduate", "course": "BTech Civil Engineering", "stream": "Civil",
     "term_type": "semester", "num_terms": 8, "age_range": (18, 23),
     "subjects": ["Structural Engineering", "Geotechnical Engineering", "Transportation Engineering",
                  "Surveying", "Concrete Technology", "Environmental Engineering"]},
    {"education_level": "Undergraduate", "course": "BTech Electronics", "stream": "Electronics",
     "term_type": "semester", "num_terms": 8, "age_range": (18, 23),
     "subjects": ["Digital Signal Processing", "Microprocessors", "VLSI Design",
                  "Communication Systems", "Control Systems", "Embedded Systems"]},
    {"education_level": "Undergraduate", "course": "MBBS", "stream": "Medical",
     "term_type": "year", "num_terms": 5, "age_range": (18, 24),
     "subjects": ["Anatomy", "Physiology", "Biochemistry", "Pathology",
                  "Pharmacology", "Microbiology", "Forensic Medicine"]},
    {"education_level": "Undergraduate", "course": "LLB", "stream": "Law",
     "term_type": "year", "num_terms": 3, "age_range": (20, 25),
     "subjects": ["Constitutional Law", "Criminal Law", "Contract Law",
                  "Law of Torts", "Jurisprudence", "Family Law"]},
    {"education_level": "Undergraduate", "course": "BBA", "stream": "Business",
     "term_type": "semester", "num_terms": 6, "age_range": (18, 22),
     "subjects": ["Principles of Management", "Marketing Management", "Financial Accounting",
                  "Business Economics", "Organizational Behavior", "Business Statistics"]},
    {"education_level": "Undergraduate", "course": "BCom", "stream": "Commerce",
     "term_type": "semester", "num_terms": 6, "age_range": (18, 22),
     "subjects": ["Financial Accounting", "Business Law", "Economics",
                  "Taxation", "Auditing", "Cost Accounting"]},
    {"education_level": "Undergraduate", "course": "BSc Science", "stream": "Science",
     "term_type": "semester", "num_terms": 6, "age_range": (18, 22),
     "subjects": ["Physics", "Chemistry", "Mathematics", "Botany", "Zoology"]},


    {"education_level": "Postgraduate", "course": "MTech Computer Science", "stream": "Computer Science",
     "term_type": "semester", "num_terms": 4, "age_range": (22, 28),
     "subjects": ["Advanced Algorithms", "Distributed Systems", "Cloud Computing",
                  "Advanced DBMS", "Advanced Operating Systems"]},
    {"education_level": "Postgraduate", "course": "MTech Artificial Intelligence", "stream": "Artificial Intelligence",
     "term_type": "semester", "num_terms": 4, "age_range": (22, 28),
     "subjects": ["Deep Learning", "Reinforcement Learning", "Advanced Natural Language Processing",
                  "Advanced Computer Vision", "Advanced Machine Learning"]},
    {"education_level": "Postgraduate", "course": "MBA", "stream": "Business",
     "term_type": "semester", "num_terms": 4, "age_range": (22, 30),
     "subjects": ["Strategic Management", "Financial Management", "Marketing Management",
                  "Human Resource Management", "Operations Management"]},
    {"education_level": "Postgraduate", "course": "MD", "stream": "Medical",
     "term_type": "year", "num_terms": 3, "age_range": (23, 30),
     "subjects": ["Advanced Pathology", "Clinical Medicine", "Surgery",
                  "Radiology", "Advanced Pharmacology"]},
    {"education_level": "Postgraduate", "course": "LLM", "stream": "Law",
     "term_type": "semester", "num_terms": 4, "age_range": (23, 30),
     "subjects": ["Advanced Constitutional Law", "International Law",
                  "Corporate Law", "Human Rights Law"]},
    {"education_level": "Postgraduate", "course": "MSc", "stream": "Science",
     "term_type": "semester", "num_terms": 4, "age_range": (22, 28),
     "subjects": ["Advanced Physics", "Advanced Chemistry", "Advanced Mathematics", "Advanced Biology"]},
]

LEARNING_GOALS = [
    "Exam Preparation", "Concept Mastery", "Skill Building", "Career Growth",
    "Competitive Exam Prep", "Grade Improvement", "Research Preparation",
    "Certification Prep", "Revision & Practice", "College Admission Prep",
]

DIFFICULTIES = ["Beginner", "Intermediate", "Advanced"]
RESOURCE_TYPES = ["Video", "Quiz", "Practice Problems", "Interactive Lab",
                   "Case Study", "Mini Project", "PDF Notes"]


TOPIC_TEMPLATES = [


    ("Introduction to {c}", "Beginner"),
    ("Fundamentals of {c}", "Beginner"),
    ("Quick Revision of {c}", "Beginner"),
    ("Essential Terminology of {c}", "Beginner"),


    ("{c}: Core Concepts", "Intermediate"),
    ("{c}: Practical Applications", "Intermediate"),
    ("Problem Solving using {c}", "Intermediate"),
    ("Common Mistakes in {c}", "Intermediate"),
    ("Hands-on Practice for {c}", "Intermediate"),


    ("Advanced {c} Techniques", "Advanced"),
    ("{c}: Case Study & Project Work", "Advanced"),
    ("Mini Project on {c}", "Advanced"),
    ("Real-world Applications of {c}", "Advanced"),
    ("Interview Questions on {c}", "Advanced"),
    ("Mastering {c}", "Advanced"),
]


CORE_TOPICS = {
    "Mathematics": ["Number Systems", "Algebra", "Geometry", "Trigonometry", "Probability & Statistics", "Calculus Basics"],
    "Science": ["Matter and Materials", "Motion and Force", "Light and Sound", "Living Organisms", "Natural Resources"],
    "English": ["Grammar Essentials", "Reading Comprehension", "Creative Writing", "Vocabulary Building", "Literature Analysis"],
    "Social Science": ["History Foundations", "Civics and Governance", "Geography Basics", "Economics Basics"],
    "Hindi": ["Vyakaran (Grammar)", "Gadya (Prose)", "Padya (Poetry)", "Lekhan Kaushal (Writing Skills)"],
    "Computer Basics": ["Computer Hardware", "Operating System Basics", "Internet Basics", "Office Applications"],
    "Physics": ["Mechanics", "Thermodynamics", "Electricity and Magnetism", "Optics", "Modern Physics", "Waves"],
    "Chemistry": ["Atomic Structure", "Chemical Bonding", "Organic Chemistry", "Periodic Table", "Chemical Reactions", "Electrochemistry"],
    "Biology": ["Cell Biology", "Genetics", "Human Physiology", "Plant Biology", "Ecology", "Evolution"],
    "Accountancy": ["Journal & Ledger", "Trial Balance", "Financial Statements", "Partnership Accounts", "Company Accounts"],
    "Business Studies": ["Business Environment", "Forms of Business", "Marketing Basics", "Business Finance"],
    "Economics": ["Microeconomics Basics", "Macroeconomics Basics", "Demand and Supply", "National Income", "Money and Banking"],
    "History": ["Ancient Civilizations", "Medieval History", "Modern History", "World Wars", "Independence Movements"],
    "Political Science": ["Political Theory", "Indian Constitution", "Comparative Politics", "International Relations"],
    "Geography": ["Physical Geography", "Human Geography", "Climatology", "Map Reading", "Resource Geography"],
    "Sociology": ["Social Structure", "Social Institutions", "Social Change", "Research Methods in Sociology"],
    "Programming Fundamentals": ["Variables and Data Types", "Control Structures", "Functions", "Arrays", "Basic I/O"],
    "Data Structures": ["Arrays and Lists", "Stacks and Queues", "Linked Lists", "Trees", "Graphs", "Hashing"],
    "DBMS": ["ER Modeling", "Relational Model", "SQL Queries", "Normalization", "Transactions", "Indexing"],
    "Web Development": ["HTML & CSS", "JavaScript Basics", "Responsive Design", "Backend Basics", "REST APIs"],
    "Computer Networks": ["Network Topologies", "OSI Model", "TCP/IP", "Routing", "Network Security"],
    "Operating Systems": ["Process Management", "Memory Management", "File Systems", "Scheduling Algorithms", "Deadlocks"],
    "Engineering Mechanics": ["Statics", "Dynamics", "Friction", "Trusses", "Center of Gravity"],
    "Thermodynamics": ["Laws of Thermodynamics", "Entropy", "Heat Engines", "Refrigeration Cycles", "Thermodynamic Properties"],
    "Machine Design": ["Design Principles", "Stress Analysis", "Fasteners", "Gears", "Bearings"],
    "Manufacturing Processes": ["Casting", "Welding", "Machining", "Forming Processes", "Quality Control"],
    "Strength of Materials": ["Stress and Strain", "Bending Moments", "Shear Force", "Torsion", "Deflection of Beams"],
    "Fluid Mechanics": ["Fluid Properties", "Fluid Statics", "Fluid Dynamics", "Flow Measurement", "Pumps and Turbines"],
    "Surveying": ["Chain Surveying", "Leveling", "Theodolite Surveying", "Total Station", "GPS Surveying"],
    "Structural Analysis": ["Determinate Structures", "Indeterminate Structures", "Influence Lines", "Slope Deflection Method"],
    "Building Materials": ["Cement and Concrete", "Bricks and Blocks", "Steel", "Timber", "Sustainable Materials"],
    "Concrete Technology": ["Concrete Mix Design", "Concrete Properties", "Curing Methods", "Reinforced Concrete"],
    "Geotechnical Engineering": ["Soil Classification", "Soil Mechanics", "Foundation Engineering", "Slope Stability"],
    "Transportation Engineering": ["Highway Design", "Traffic Engineering", "Pavement Design", "Railway Engineering"],
    "Circuit Theory": ["Circuit Laws", "AC Circuits", "DC Circuits", "Network Theorems", "Resonance"],
    "Digital Electronics": ["Logic Gates", "Boolean Algebra", "Combinational Circuits", "Sequential Circuits", "Counters"],
    "Microprocessors": ["8085 Architecture", "Instruction Sets", "Interfacing", "Interrupts", "Memory Organization"],
    "Communication Systems": ["Modulation Techniques", "Analog Communication", "Digital Communication", "Antennas"],
    "Electronic Devices": ["Diodes", "Transistors", "Amplifiers", "Oscillators", "Power Electronics Basics"],
    "Control Systems": ["Transfer Functions", "Block Diagrams", "Stability Analysis", "PID Controllers", "State Space Analysis"],
    "OOP": ["Classes and Objects", "Inheritance", "Polymorphism", "Encapsulation", "Abstraction", "Design Patterns"],
    "Algorithms": ["Sorting Algorithms", "Searching Algorithms", "Dynamic Programming", "Greedy Algorithms", "Graph Algorithms"],
    "Software Engineering": ["SDLC Models", "Requirements Engineering", "Software Testing", "Agile Methodology", "Software Design"],
    "Web Technologies": ["Frontend Frameworks", "Backend Frameworks", "APIs and Microservices", "Web Security"],
    "Machine Learning": ["Supervised Learning", "Unsupervised Learning", "Model Evaluation", "Feature Engineering", "Ensemble Methods"],
    "Deep Learning": ["Neural Networks", "Convolutional Networks", "Recurrent Networks", "Transformers", "Optimization Techniques"],
    "Statistics": ["Descriptive Statistics", "Probability Distributions", "Hypothesis Testing", "Regression Analysis", "Sampling Methods"],
    "Natural Language Processing": ["Text Preprocessing", "Word Embeddings", "Sequence Models", "Language Models", "Sentiment Analysis"],
    "Computer Vision": ["Image Processing", "Feature Extraction", "Object Detection", "Image Segmentation", "CNN Architectures"],
    "Reinforcement Learning": ["Markov Decision Processes", "Q-Learning", "Policy Gradients", "Value Functions", "Exploration Strategies"],
    "Heat Transfer": ["Conduction", "Convection", "Radiation", "Heat Exchangers", "Boiling and Condensation"],
    "Structural Engineering": ["Load Analysis", "Beam Design", "Column Design", "Earthquake Engineering", "Steel Structures"],
    "Environmental Engineering": ["Water Treatment", "Air Pollution Control", "Solid Waste Management", "Environmental Impact Assessment"],
    "Digital Signal Processing": ["Signal Sampling", "Fourier Transform", "Filters", "Z-Transform", "Spectral Analysis"],
    "VLSI Design": ["CMOS Design", "Layout Design", "Fabrication Process", "Timing Analysis", "Verification"],
    "Embedded Systems": ["Microcontrollers", "RTOS Basics", "Sensor Interfacing", "Embedded C Programming"],
    "Anatomy": ["Skeletal System", "Muscular System", "Nervous System", "Cardiovascular System", "Respiratory System"],
    "Physiology": ["Cell Physiology", "Cardiovascular Physiology", "Respiratory Physiology", "Renal Physiology", "Endocrine Physiology"],
    "Biochemistry": ["Carbohydrates", "Proteins and Enzymes", "Lipids", "Metabolism", "Molecular Biology Basics"],
    "Pathology": ["Cell Injury", "Inflammation", "Neoplasia", "Systemic Pathology", "Hematopathology"],
    "Pharmacology": ["Pharmacokinetics", "Pharmacodynamics", "Autonomic Drugs", "Antimicrobial Agents", "CNS Drugs"],
    "Microbiology": ["Bacteriology", "Virology", "Mycology", "Immunology Basics", "Parasitology"],
    "Forensic Medicine": ["Medico-legal Aspects", "Injuries and Wounds", "Toxicology", "Autopsy Procedures"],
    "Constitutional Law": ["Fundamental Rights", "Directive Principles", "Separation of Powers", "Constitutional Amendments"],
    "Criminal Law": ["Elements of Crime", "Offences Against Person", "Offences Against Property", "Criminal Procedure"],
    "Contract Law": ["Formation of Contracts", "Breach of Contract", "Remedies", "Special Contracts"],
    "Law of Torts": ["Negligence", "Defamation", "Strict Liability", "Vicarious Liability"],
    "Jurisprudence": ["Schools of Jurisprudence", "Legal Rights and Duties", "Sources of Law", "Theories of Justice"],
    "Family Law": ["Marriage Laws", "Divorce and Maintenance", "Succession Laws", "Adoption and Guardianship"],
    "Principles of Management": ["Planning", "Organizing", "Staffing", "Directing", "Controlling"],
    "Marketing Management": ["Marketing Mix", "Consumer Behavior", "Market Segmentation", "Branding", "Digital Marketing"],
    "Financial Accounting": ["Accounting Principles", "Financial Statements", "Depreciation", "Cash Flow Statements"],
    "Business Economics": ["Demand Analysis", "Cost Analysis", "Market Structures", "Pricing Strategies"],
    "Organizational Behavior": ["Individual Behavior", "Group Dynamics", "Leadership", "Organizational Culture"],
    "Business Statistics": ["Data Collection", "Measures of Central Tendency", "Correlation and Regression", "Index Numbers"],
    "Business Law": ["Contract Act Basics", "Sale of Goods Act", "Company Law Basics", "Negotiable Instruments"],
    "Taxation": ["Income Tax Basics", "GST Fundamentals", "Tax Planning", "Corporate Taxation"],
    "Auditing": ["Audit Principles", "Internal Control", "Vouching", "Audit Report Writing"],
    "Cost Accounting": ["Cost Concepts", "Costing Methods", "Budgetary Control", "Standard Costing"],
    "Botany": ["Plant Morphology", "Plant Physiology", "Plant Taxonomy", "Plant Ecology"],
    "Zoology": ["Animal Diversity", "Animal Physiology", "Developmental Biology", "Animal Behavior"],
    "Advanced Algorithms": ["Amortized Analysis", "NP-Completeness", "Approximation Algorithms", "Randomized Algorithms"],
    "Distributed Systems": ["Distributed Consensus", "Replication", "Fault Tolerance", "Distributed File Systems"],
    "Cloud Computing": ["Cloud Service Models", "Virtualization", "Container Orchestration", "Cloud Security"],
    "Advanced DBMS": ["Query Optimization", "Concurrency Control", "Distributed Databases", "NoSQL Systems"],
    "Advanced Operating Systems": ["Virtual Memory Management", "Distributed OS", "Real-Time Systems", "Kernel Design"],
    "Advanced Natural Language Processing": ["Large Language Models", "Attention Mechanisms", "Text Generation", "Machine Translation"],
    "Advanced Computer Vision": ["Object Tracking", "3D Vision", "Generative Vision Models", "Video Understanding"],
    "Advanced Machine Learning": ["Bayesian Learning", "Kernel Methods", "Model Interpretability", "AutoML"],
    "Strategic Management": ["Strategy Formulation", "Competitive Analysis", "Strategy Implementation", "Corporate Governance"],
    "Financial Management": ["Capital Budgeting", "Working Capital Management", "Risk and Return", "Dividend Policy"],
    "Human Resource Management": ["Recruitment and Selection", "Training and Development", "Performance Management", "Compensation"],
    "Operations Management": ["Process Design", "Inventory Management", "Quality Management", "Supply Chain Management"],
    "Advanced Pathology": ["Molecular Pathology", "Tumor Biology", "Autoimmune Pathology", "Forensic Pathology"],
    "Clinical Medicine": ["Cardiology Basics", "Respiratory Medicine", "Gastroenterology", "Endocrinology"],
    "Surgery": ["Pre-operative Care", "Surgical Techniques", "Post-operative Care", "Trauma Surgery"],
    "Radiology": ["X-Ray Interpretation", "CT Imaging", "MRI Basics", "Ultrasound Techniques"],
    "Advanced Pharmacology": ["Drug Interactions", "Clinical Pharmacology", "Pharmacogenomics", "Adverse Drug Reactions"],
    "Advanced Constitutional Law": ["Judicial Review", "Federalism", "Emergency Provisions", "Comparative Constitutional Law"],
    "International Law": ["Treaties and Conventions", "International Organizations", "Law of the Sea", "Human Rights Law Basics"],
    "Corporate Law": ["Company Formation", "Corporate Governance", "Mergers and Acquisitions", "Insolvency Law"],
    "Human Rights Law": ["Civil and Political Rights", "Economic and Social Rights", "International Human Rights Bodies"],
    "Advanced Physics": ["Quantum Mechanics", "Statistical Mechanics", "Relativity", "Nuclear Physics"],
    "Advanced Chemistry": ["Spectroscopy", "Reaction Kinetics", "Coordination Chemistry", "Polymer Chemistry"],
    "Advanced Mathematics": ["Real Analysis", "Abstract Algebra", "Complex Analysis", "Numerical Methods"],
    "Advanced Biology": ["Molecular Genetics", "Genomics", "Bioinformatics Basics", "Systems Biology"],
}


def core_topics_for(subject):
    """Return curated core concepts for a subject, generic fallback otherwise."""
    if subject in CORE_TOPICS:
        return CORE_TOPICS[subject]
    return [f"{subject} Concept {i}" for i in range(1, 6)]

**2. DETERMINING CATALOGS**

In [116]:

def build_subject_catalog():
    """One row per unique (Education_Level, Course, Subject) combination."""
    rows = []
    for entry in CURRICULUM:
        for subject in entry["subjects"]:
            rows.append({
                "Education_Level": entry["education_level"],
                "Course": entry["course"],
                "Stream": entry["stream"] if entry["stream"] else "General",
                "Subject": subject,
            })
    df = pd.DataFrame(rows).drop_duplicates().reset_index(drop=True)
    return df

In [117]:

def build_topic_catalog(subject_catalog):
    """
    For every unique subject, expand its curated core concepts through
    TOPIC_TEMPLATES to build a beginner->advanced topic sequence with a
    logically chained Prerequisite field.
    """
    unique_subjects = sorted(subject_catalog["Subject"].unique())
    rows = []

    resource_by_difficulty = {
        "Beginner": ["Video", "PDF Notes", "Quiz"],
        "Intermediate": ["Quiz", "Practice Problems", "Video", "Case Study"],
        "Advanced": ["Interactive Lab", "Mini Project", "Case Study", "Practice Problems"],
    }
    time_by_difficulty = {"Beginner": (15, 30), "Intermediate": (30, 60), "Advanced": (60, 120)}
    skill_by_difficulty = {"Beginner": (1, 2), "Intermediate": (2, 4), "Advanced": (4, 5)}

    for subject in unique_subjects:
        concepts = core_topics_for(subject)
        previous_topic = None
        for concept in concepts:
            for template, difficulty in TOPIC_TEMPLATES:
                topic_name = template.format(c=concept)
                lo, hi = time_by_difficulty[difficulty]
                est_time = int(np.random.randint(lo, hi + 1))
                lo_s, hi_s = skill_by_difficulty[difficulty]
                skill_level = int(np.random.randint(lo_s, hi_s + 1))
                resource = np.random.choice(resource_by_difficulty[difficulty])

                rows.append({
                    "Subject": subject,
                    "Topic": topic_name,
                    "Difficulty": difficulty,
                    "Estimated_Time": est_time,
                    "Prerequisite": previous_topic if previous_topic else "None",
                    "Skill_Level": skill_level,
                })
                previous_topic = topic_name

    df = pd.DataFrame(rows)
    df = df.drop_duplicates(subset=["Subject", "Topic"]).reset_index(drop=True)
    return df

In [118]:

def build_student_profiles(n_students=10000):
    rows = []

    level_weights = {"Grade 6-12": 0.45, "Diploma": 0.10, "Undergraduate": 0.35, "Postgraduate": 0.10}
    entries_by_level = {lvl: [e for e in CURRICULUM if e["education_level"] == lvl] for lvl in level_weights}

    levels = list(level_weights.keys())
    weights = list(level_weights.values())

    for i in range(1, n_students + 1):
        student_id = f"S{i:05d}"
        level = np.random.choice(levels, p=weights)
        entry = random.choice(entries_by_level[level])

        age_lo, age_hi = entry["age_range"]
        age = int(np.random.randint(age_lo, age_hi + 1))

        course_label = entry["course"]
        if entry["stream"] and "Grade" in entry["course"]:
            course_label = f'{entry["course"]} - {entry["stream"]}'

        if entry["term_type"] == "grade":
            semester_label = "Annual"
        elif entry["term_type"] == "year":
            semester_label = f"Year {np.random.randint(1, entry['num_terms'] + 1)}"
        else:
            semester_label = f"Semester {np.random.randint(1, entry['num_terms'] + 1)}"

        registered_subjects = entry["subjects"]

        rows.append({
            "Student_ID": student_id,
            "Student_Name": generate_name(),
            "Age": age,
            "Education_Level": entry["education_level"],
            "Course": course_label,
            "Semester": semester_label,
            "Registered_Subjects": "; ".join(registered_subjects),
            "Learning_Goal": np.random.choice(LEARNING_GOALS),
        })

    df = pd.DataFrame(rows)
    assert df["Student_ID"].is_unique, "Duplicate Student_ID generated!"
    return df, entries_by_level

In [119]:

def build_learning_history(student_df, topic_catalog, n_records=50000):
    """
    Simulates realistic study sessions:
      * A student only studies subjects they are registered in.
      * Topics within a subject are studied in curriculum sequence
        (mirrors prerequisite-respecting recommendations).
      * Engagement is skewed: a minority of (student, subject) pairs
        generate a disproportionate share of activity, like real LMS logs.
    """
    topics_by_subject = (
        topic_catalog.groupby("Subject")["Topic"].apply(list).to_dict()
    )
    est_time_lookup = dict(zip(
        zip(topic_catalog["Subject"], topic_catalog["Topic"]),
        topic_catalog["Estimated_Time"],
    ))

    pairs = []
    for _, srow in student_df.iterrows():
        student_id = srow["Student_ID"]
        subjects = srow["Registered_Subjects"].split("; ")
        for subj in subjects:
            if subj in topics_by_subject:
                pairs.append((student_id, subj))

    n_pairs = len(pairs)

    weights = np.random.exponential(scale=1.0, size=n_pairs)
    weights = weights / weights.sum()

    sampled_idx = np.random.choice(n_pairs, size=n_records, p=weights, replace=True)

    from collections import defaultdict
    session_counter = defaultdict(int)
    start_dates = {}
    rows = []

    today = datetime(2025, 6, 1)

    for idx in sampled_idx:
        student_id, subject = pairs[idx]
        session_counter[idx] += 1
        seq = session_counter[idx]

        topics = topics_by_subject[subject]
        n_topics = len(topics)

        current_topic = topics[(seq - 1) % n_topics]
        previous_topic = topics[(seq - 2) % n_topics] if seq > 1 else "None (Initial Assessment)"

        attempts = int(np.clip(np.round(np.random.exponential(1.4)) + 1, 1, 6))
        quiz_score = float(np.clip(np.random.normal(78 - 3 * (attempts - 1), 14), 0, 100))
        quiz_score = round(quiz_score, 1)

        base_time = est_time_lookup.get((subject, current_topic), 30)
        time_spent = int(np.clip(base_time * np.random.uniform(0.6, 1.9), 5, 240))

        topics_completed = min(seq, n_topics)
        learning_progress = round(topics_completed / n_topics, 2)

        if quiz_score >= 75:
            status = "Completed"
        elif quiz_score >= 40:
            status = "In Progress"
        else:
            status = "Needs Revision"

        if idx not in start_dates:
            start_dates[idx] = today - timedelta(days=int(np.random.randint(30, 540)))
        study_date = start_dates[idx] + timedelta(days=int(seq * np.random.randint(2, 12)))
        if study_date > today:
            study_date = today - timedelta(days=int(np.random.randint(0, 5)))

        rows.append({
            "Student_ID": student_id,
            "Subject": subject,
            "Topic": current_topic,
            "Quiz_Score": quiz_score,
            "Topics_Completed": topics_completed,
            "Time_Spent_Per_Topic": time_spent,
            "Attempts": attempts,
            "Learning_Progress": learning_progress,
            "Previous_Recommendation": previous_topic,
            "Completion_Status": status,
            "Study_Date": study_date.strftime("%Y-%m-%d"),
        })

    df = pd.DataFrame(rows)
    return df

In [120]:

def build_resource_catalog(topic_catalog):
    rows = []
    resource_name_bank = {
        "Video": ["Explainer Video", "Concept Walkthrough", "Lecture Recording"],
        "Quiz": ["Quick Check Quiz", "Chapter-End Quiz", "Adaptive Quiz"],
        "Practice Problems": ["Practice Problem Set", "Drill Exercises", "Worksheet"],
        "Interactive Lab": ["Virtual Lab", "Interactive Simulation", "Hands-on Lab"],
        "Case Study": ["Real-World Case Study", "Applied Case Analysis"],
        "Mini Project": ["Guided Mini Project", "Capstone Mini Project"],
        "PDF Notes": ["Concise Notes PDF", "Detailed Study Notes"],
    }

    for _, row in topic_catalog.iterrows():
        subject, topic, difficulty = row["Subject"], row["Topic"], row["Difficulty"]
        n_resources = np.random.randint(1, 3)
        chosen_types = np.random.choice(RESOURCE_TYPES, size=n_resources, replace=False)

        for r_type in chosen_types:
            base_name = np.random.choice(resource_name_bank[r_type])
            resource_name = f"{base_name}: {topic}"
            duration = int(np.random.randint(5, 90))
            rating = round(float(np.clip(np.random.normal(4.2, 0.5), 2.5, 5.0)), 1)
            url = f"https://lms.example.com/resources/{slugify(subject)}/{slugify(topic)}/{slugify(r_type)}"

            rows.append({
                "Topic": topic,
                "Resource_Name": resource_name,
                "Resource_Type": r_type,
                "Difficulty": difficulty,
                "Duration": duration,
                "Rating": rating,
                "URL_Placeholder": url,
            })

    return pd.DataFrame(rows)

In [121]:

def validate(student_df, subject_df, topic_df, history_df, resource_df):
    errors = []

    if not student_df["Student_ID"].is_unique:
        errors.append("Duplicate Student_ID found in student_profiles.")

    valid_subjects = set(subject_df["Subject"])
    hist_subjects = set(history_df["Subject"])
    if not hist_subjects.issubset(valid_subjects):
        errors.append("learning_history references subjects not in subject_catalog.")

    valid_topics = set(zip(topic_df["Subject"], topic_df["Topic"]))
    hist_topics = set(zip(history_df["Subject"], history_df["Topic"]))
    if not hist_topics.issubset(valid_topics):
        errors.append("learning_history references (Subject, Topic) pairs not in topic_catalog.")

    valid_resource_topics = set(topic_df["Topic"])
    if not set(resource_df["Topic"]).issubset(valid_resource_topics):
        errors.append("resource_catalog references topics not in topic_catalog.")


    student_subjects = student_df.set_index("Student_ID")["Registered_Subjects"].to_dict()
    sample = history_df.sample(min(2000, len(history_df)), random_state=SEED)
    bad = sample[~sample.apply(
        lambda r: r["Subject"] in student_subjects.get(r["Student_ID"], "").split("; "), axis=1
    )]
    if len(bad) > 0:
        errors.append(f"{len(bad)} learning_history rows study a subject outside the student's registration.")

    if len(topic_df) < 3000:
        errors.append(f"topic_catalog has only {len(topic_df)} rows (< 3000 requirement).")

    if errors:
        raise AssertionError("Data validation failed:\n- " + "\n- ".join(errors))

    print("✔ All consistency checks passed.")

**3. DATASET GENERATION**

In [122]:

def main(n_students=10000, n_history_records=50000):
    print("Building subject_catalog ...")
    subject_catalog = build_subject_catalog()

    print("Building topic_catalog ...")
    topic_catalog = build_topic_catalog(subject_catalog)

    print("Building student_profiles ...")
    student_profiles, _ = build_student_profiles(n_students)

    print("Building learning_history ...")
    learning_history = build_learning_history(student_profiles, topic_catalog, n_history_records)

    print("Building resource_catalog ...")
    resource_catalog = build_resource_catalog(topic_catalog)

    print("Validating referential integrity ...")
    validate(student_profiles, subject_catalog, topic_catalog, learning_history, resource_catalog)

    print("Saving CSV files ...")
    student_profiles.to_csv(os.path.join(OUTPUT_DIR, "student_profiles.csv"), index=False)
    subject_catalog.to_csv(os.path.join(OUTPUT_DIR, "subject_catalog.csv"), index=False)
    topic_catalog.to_csv(os.path.join(OUTPUT_DIR, "topic_catalog.csv"), index=False)
    learning_history.to_csv(os.path.join(OUTPUT_DIR, "learning_history.csv"), index=False)
    resource_catalog.to_csv(os.path.join(OUTPUT_DIR, "resource_catalog.csv"), index=False)

    print("\n===== SUMMARY =====")
    print(f"student_profiles.csv : {len(student_profiles):,} rows")
    print(f"subject_catalog.csv  : {len(subject_catalog):,} rows")
    print(f"topic_catalog.csv    : {len(topic_catalog):,} rows")
    print(f"learning_history.csv : {len(learning_history):,} rows")
    print(f"resource_catalog.csv : {len(resource_catalog):,} rows")
    print(f"\nAll files saved to ./{OUTPUT_DIR}/")


if __name__ == "__main__":
    main(n_students=10000, n_history_records=50000)

Building subject_catalog ...
Building topic_catalog ...
Building student_profiles ...
Building learning_history ...
Building resource_catalog ...
Validating referential integrity ...
✔ All consistency checks passed.
Saving CSV files ...

===== SUMMARY =====
student_profiles.csv : 10,000 rows
subject_catalog.csv  : 171 rows
topic_catalog.csv    : 7,200 rows
learning_history.csv : 50,000 rows
resource_catalog.csv : 10,808 rows

All files saved to ./lms_dataset/

# **PHASE 2: FEATURE ANALYSIS**

In [123]:
students = pd.read_csv("lms_dataset/student_profiles.csv")
subjects = pd.read_csv("lms_dataset/subject_catalog.csv")
topics = pd.read_csv("lms_dataset/topic_catalog.csv")
history = pd.read_csv("lms_dataset/learning_history.csv")
resources = pd.read_csv("lms_dataset/resource_catalog.csv")

In [124]:
print("Students :", students.shape)
print("Subjects :", subjects.shape)
print("Topics :", topics.shape)
print("History :", history.shape)
print("Resources :", resources.shape)

Students : (10000, 8)
Subjects : (171, 4)
Topics : (7200, 6)
History : (50000, 11)
Resources : (10808, 7)

In [125]:
students.head()

,Student_ID,Student_Name,Age,Education_Level,Course,Semester,Registered_Subjects,Learning_Goal
0,S00001,Allison Hill,28,Postgraduate,MSc,Semester 3,Advanced Physics; Advanced Chemistry; Advanced...,Certification Prep
1,S00002,Noah Rhodes,18,Undergraduate,BTech Artificial Intelligence,Semester 4,Machine Learning; Deep Learning; Statistics; O...,Certification Prep
2,S00003,Angie Henderson,11,Grade 6-12,Grade 6,Annual,Mathematics; Science; English; Social Science;...,College Admission Prep
3,S00004,Daniel Wagner,18,Undergraduate,BTech Electronics,Semester 4,Digital Signal Processing; Microprocessors; VL...,Concept Mastery
4,S00005,Cristian Santos,15,Grade 6-12,Grade 9,Annual,Mathematics; Science; English; Social Science;...,Research Preparation

In [126]:
subjects.head()

  Education_Level   Course   Stream         Subject
0      Grade 6-12  Grade 6  General     Mathematics
1      Grade 6-12  Grade 6  General         Science
2      Grade 6-12  Grade 6  General         English
3      Grade 6-12  Grade 6  General  Social Science
4      Grade 6-12  Grade 6  General           Hindi

In [127]:
history.head()

,Student_ID,Subject,Topic,Quiz_Score,Topics_Completed,Time_Spent_Per_Topic,Attempts,Learning_Progress,Previous_Recommendation,Completion_Status,Study_Date
0,S08871,Manufacturing Processes,Introduction to Casting,82.2,1,15,1,0.01,None (Initial Assessment),Completed,2025-04-19
1,S09059,Accountancy,Introduction to Journal & Ledger,84.6,1,36,1,0.01,None (Initial Assessment),Completed,2023-12-16
2,S01569,Transportation Engineering,Introduction to Highway Design,71.5,1,20,1,0.02,None (Initial Assessment),In Progress,2024-06-09
3,S07799,Social Science,Introduction to History Foundations,63.1,1,15,2,0.02,None (Initial Assessment),In Progress,2024-05-28
4,S04724,Software Engineering,Introduction to SDLC Models,51.5,1,11,3,0.01,None (Initial Assessment),In Progress,2024-07-23

In [128]:
topics.head()

,Subject,Topic,Difficulty,Estimated_Time,Prerequisite,Skill_Level
0,Accountancy,Introduction to Journal & Ledger,Beginner,21,NaN,2
1,Accountancy,Fundamentals of Journal & Ledger,Beginner,29,Introduction to Journal & Ledger,1
2,Accountancy,Quick Revision of Journal & Ledger,Beginner,19,Fundamentals of Journal & Ledger,1
3,Accountancy,Essential Terminology of Journal & Ledger,Beginner,17,Quick Revision of Journal & Ledger,1
4,Accountancy,Journal & Ledger: Core Concepts,Intermediate,40,Essential Terminology of Journal & Ledger,2

In [129]:
resources.head()

,Topic,Resource_Name,Resource_Type,Difficulty,Duration,Rating,URL_Placeholder
0,Introduction to Journal & Ledger,Detailed Study Notes: Introduction to Journal ...,PDF Notes,Beginner,26,3.6,https://lms.example.com/resources/accountancy/...
1,Fundamentals of Journal & Ledger,Real-World Case Study: Fundamentals of Journal...,Case Study,Beginner,21,5.0,https://lms.example.com/resources/accountancy/...
2,Fundamentals of Journal & Ledger,Adaptive Quiz: Fundamentals of Journal & Ledger,Quiz,Beginner,64,3.7,https://lms.example.com/resources/accountancy/...
3,Quick Revision of Journal & Ledger,Guided Mini Project: Quick Revision of Journal...,Mini Project,Beginner,59,3.8,https://lms.example.com/resources/accountancy/...
4,Quick Revision of Journal & Ledger,Real-World Case Study: Quick Revision of Journ...,Case Study,Beginner,64,4.5,https://lms.example.com/resources/accountancy/...

In [130]:
print(students.columns.tolist())
print(subjects.columns.tolist())
print(topics.columns.tolist())
print(history.columns.tolist())
print(resources.columns.tolist())

['Student_ID', 'Student_Name', 'Age', 'Education_Level', 'Course', 'Semester', 'Registered_Subjects', 'Learning_Goal']
['Education_Level', 'Course', 'Stream', 'Subject']
['Subject', 'Topic', 'Difficulty', 'Estimated_Time', 'Prerequisite', 'Skill_Level']
['Student_ID', 'Subject', 'Topic', 'Quiz_Score', 'Topics_Completed', 'Time_Spent_Per_Topic', 'Attempts', 'Learning_Progress', 'Previous_Recommendation', 'Completion_Status', 'Study_Date']
['Topic', 'Resource_Name', 'Resource_Type', 'Difficulty', 'Duration', 'Rating', 'URL_Placeholder']

# **PHASE 3: ENGINE ESTABLISHMENT**

**1. SCALING VERIFICATION**

In [131]:
def get_student(student_id):
    """
    Returns complete student profile.
    """
    student = students[students["Student_ID"] == student_id]

    if student.empty:
        return None

    return student.iloc[0]

In [132]:
students.iloc[0]["Student_ID"]
student = get_student("S00001")

student

Student_ID                                                        S00001
Student_Name                                                Allison Hill
Age                                                                   28
Education_Level                                             Postgraduate
Course                                                               MSc
Semester                                                      Semester 3
Registered_Subjects    Advanced Physics; Advanced Chemistry; Advanced...
Learning_Goal                                         Certification Prep
Name: 0, dtype: object

In [133]:
def get_learning_history(student_id):

    history_df = history[
        history["Student_ID"] == student_id
    ]

    return history_df

In [134]:
history_df = get_learning_history("S00001")
history_df.head()

,Student_ID,Subject,Topic,Quiz_Score,Topics_Completed,Time_Spent_Per_Topic,Attempts,Learning_Progress,Previous_Recommendation,Completion_Status,Study_Date
2994,S00001,Advanced Chemistry,Introduction to Spectroscopy,80.2,1,32,2,0.02,None (Initial Assessment),Completed,2025-04-17
3751,S00001,Advanced Biology,Introduction to Molecular Genetics,76.2,1,19,1,0.02,None (Initial Assessment),Completed,2024-09-20
12341,S00001,Advanced Biology,Fundamentals of Molecular Genetics,68.9,2,16,2,0.03,Introduction to Molecular Genetics,In Progress,2024-09-24
17799,S00001,Advanced Chemistry,Fundamentals of Spectroscopy,79.4,2,23,1,0.03,Introduction to Spectroscopy,Completed,2025-04-27
20080,S00001,Advanced Mathematics,Introduction to Real Analysis,77.6,1,10,3,0.02,None (Initial Assessment),Completed,2024-01-09

In [135]:
def get_registered_subjects(student):

    return student["Registered_Subjects"]

In [136]:
student = get_student("S00001")

print(get_registered_subjects(student))

Advanced Physics; Advanced Chemistry; Advanced Mathematics; Advanced Biology

In [137]:
def get_topics(subject):

    return topics[
        topics["Subject"] == subject
    ]

In [138]:
subject = subjects.iloc[0]["Subject"]

get_topics(subject).head()

,Subject,Topic,Difficulty,Estimated_Time,Prerequisite,Skill_Level
4725,Mathematics,Introduction to Number Systems,Beginner,26,NaN,1
4726,Mathematics,Fundamentals of Number Systems,Beginner,17,Introduction to Number Systems,1
4727,Mathematics,Quick Revision of Number Systems,Beginner,20,Fundamentals of Number Systems,2
4728,Mathematics,Essential Terminology of Number Systems,Beginner,23,Quick Revision of Number Systems,2
4729,Mathematics,Number Systems: Core Concepts,Intermediate,58,Essential Terminology of Number Systems,4

In [139]:
def get_resources(topic):

    return resources[
        resources["Topic"] == topic
    ]

In [140]:
topic = topics.iloc[0]["Topic"]

get_resources(topic)

,Topic,Resource_Name,Resource_Type,Difficulty,Duration,Rating,URL_Placeholder
0,Introduction to Journal & Ledger,Detailed Study Notes: Introduction to Journal ...,PDF Notes,Beginner,26,3.6,https://lms.example.com/resources/accountancy/...

**2. XGBOOST INFERENCE BRIDGE**

In [141]:
import joblib

xgb_model = joblib.load("xgboost_model.pkl")
preprocessor = joblib.load("preprocessor.pkl")

print("XGBoost model loaded successfully")
print("Preprocessor loaded successfully")
print("Model type:", type(xgb_model))
print("Preprocessor type:", type(preprocessor))

XGBoost model loaded successfully
Preprocessor loaded successfully
Model type: <class 'xgboost.sklearn.XGBClassifier'>
Preprocessor type: <class 'sklearn.compose._column_transformer.ColumnTransformer'>

In [142]:
print("=" * 60)
print("XGBOOST ARTIFACT CHECK")
print("=" * 60)

print("Model classes:")
print(xgb_model.classes_)

print("\nNumber of model features:")
print(xgb_model.n_features_in_)

print("\nArtifacts are available for inference.")

============================================================
XGBOOST ARTIFACT CHECK
============================================================
Model classes:
[0 1 2 3]

Number of model features:
78

Artifacts are available for inference.

In [143]:
print("=" * 60)
print("XGBOOST MODEL READY")
print("=" * 60)

print("Classes:", xgb_model.classes_)
print("Expected input features:", xgb_model.n_features_in_)

print("\nALIE recommendation engine remains independent.")
print("No recommendation logic has been changed.")

============================================================
XGBOOST MODEL READY
============================================================
Classes: [0 1 2 3]
Expected input features: 78

ALIE recommendation engine remains independent.
No recommendation logic has been changed.

In [144]:
print(xgb_model.classes_)
print(xgb_model.n_features_in_)

[0 1 2 3]
78

# **PHASE 4: ADAPTIVE LEARNING INTELLIGENCE ENGINE [ALIE]**

**1. FOUNDATION OF ALIE**

In [145]:
def parse_subjects(subject_string):
    """
    Convert semicolon separated subjects into a Python list.
    """

    return [s.strip() for s in subject_string.split(";")]

In [146]:
student = get_student("S00001")

parse_subjects(student["Registered_Subjects"])

['Advanced Physics',
 'Advanced Chemistry',
 'Advanced Mathematics',
 'Advanced Biology']

In [147]:
def find_weak_subjects(student_id):

    student_history = get_learning_history(student_id)

    weakness = (
        student_history
        .groupby("Subject")["Quiz_Score"]
        .mean()
        .sort_values()
    )

    return weakness

In [148]:
find_weak_subjects("S00001")

Subject
Advanced Biology        72.70
Advanced Mathematics    75.25
Advanced Chemistry      81.00
Name: Quiz_Score, dtype: float64

In [149]:
def latest_topic(student_id, subject):

    df = get_learning_history(student_id)

    df = df[df["Subject"] == subject]

    if df.empty:
        return None

    latest = df.sort_values("Study_Date")

    return latest.iloc[-1]["Topic"]

In [150]:
latest_topic("S00001","Advanced Chemistry")

'Quick Revision of Spectroscopy'

In [151]:
def next_topics(current_topic):

    return topics[
        topics["Prerequisite"] == current_topic
    ]

In [152]:
current = latest_topic("S00001","Advanced Chemistry")

next_topics(current)

,Subject,Topic,Difficulty,Estimated_Time,Prerequisite,Skill_Level
198,Advanced Chemistry,Essential Terminology of Spectroscopy,Beginner,19,Quick Revision of Spectroscopy,2

In [153]:
def best_resource(topic):

    df = resources[
        resources["Topic"] == topic
    ]

    if df.empty:
        return None

    return df.sort_values(
        "Rating",
        ascending=False
    ).iloc[0]

In [154]:
candidate = next_topics(current)
topic_name = candidate.iloc[0]["Topic"]

best_resource(topic_name)

Topic                          Essential Terminology of Spectroscopy
Resource_Name       Worksheet: Essential Terminology of Spectroscopy
Resource_Type                                      Practice Problems
Difficulty                                                  Beginner
Duration                                                          47
Rating                                                           4.1
URL_Placeholder    https://lms.example.com/resources/advanced-che...
Name: 292, dtype: object

In [155]:
def recommendation_confidence(
        quiz,
        progress,
        rating):

    confidence = (
        0.30*quiz +
        0.40*(progress*100) +
        0.30*(rating*20)
    )

    return round(min(confidence,100),2)

In [156]:
def motivational_message(score):

    if score>=90:

        return (
            "Outstanding progress! "
            "You're ready to challenge yourself with advanced concepts."
        )

    elif score>=75:

        return (
            "Great consistency! "
            "Keep building on your strengths while improving weaker areas."
        )

    elif score>=60:

        return (
            "Good effort! "
            "Focus on completing prerequisite topics before moving ahead."
        )

    else:

        return (
            "Don't worry. Every expert started as a beginner. "
            "Let's strengthen the fundamentals step by step."
        )

**2. DEPLOYING THE ALIE**

In [157]:
def calculate_learning_health(student_id):

    history_df = get_learning_history(student_id)

    if history_df.empty:
        return 0.0

    avg_quiz = history_df["Quiz_Score"].fillna(0).mean()

    progress = history_df["Learning_Progress"].fillna(0).max() * 100

    avg_topics = history_df["Topics_Completed"].fillna(0).max()

    completion_rate = (
        (history_df["Completion_Status"] == "Completed").mean() * 100
    )

    avg_attempts = history_df["Attempts"].fillna(1).mean()

    topic_score = min((avg_topics / 10) * 100, 100)

    attempt_score = max(100 - (avg_attempts - 1) * 15, 40)

    health = (
        avg_quiz * 0.35
        + progress * 0.30
        + topic_score * 0.15
        + completion_rate * 0.10
        + attempt_score * 0.10
    )

    return round(min(100, health), 1)

In [158]:
def generate_reason(subject,
                    quiz_score,
                    progress):

    reasons=[]

    if quiz_score<70:
        reasons.append(
            "Low quiz performance detected."
        )

    elif quiz_score<85:
        reasons.append(
            "Moderate understanding; strengthening this topic will improve consistency."
        )

    else:
        reasons.append(
            "Strong foundation. Ready for advanced learning."
        )

    if progress<50:
        reasons.append(
            "Learning progress is still developing."
        )

    else:
        reasons.append(
            "Prerequisite concepts have already been completed."
        )

    return reasons

In [159]:
def expected_gain(difficulty):

    gains={
        "Beginner":12,
        "Intermediate":8,
        "Advanced":5
    }

    return gains[difficulty]

In [160]:
def recommendation_priority(confidence):

    if confidence>=90:
        return "High"

    elif confidence>=75:
        return "Medium"

    else:
        return "Low"

In [161]:
def generate_learning_path(student_id):

    student = get_student(student_id)

    if student is None:
        return "Student not found."

    registered_subjects = parse_subjects(
        student["Registered_Subjects"]
    )

    weak_subjects = find_weak_subjects(student_id)

    recommendations = []

    for subject in weak_subjects.index:

        current_topic = latest_topic(student_id, subject)

        if current_topic is None:
            continue

        candidate_topics = next_topics(current_topic)

        if candidate_topics.empty:
            continue

        next_topic = candidate_topics.iloc[0]

        topic_name = next_topic["Topic"]

        resource = best_resource(topic_name)

        if resource is None:
            continue

        history_df = get_learning_history(student_id)

        history_subject = history_df[
            history_df["Subject"] == subject
        ]

        avg_quiz = history_subject["Quiz_Score"].mean()

        avg_progress = history_subject[
            "Learning_Progress"
        ].mean()

        confidence = recommendation_confidence(
            avg_quiz,
            avg_progress,
            resource["Rating"]
        )

        recommendations.append({

    "Subject": subject,

    "Current Topic": current_topic,

    "Next Topic": topic_name,

    "Difficulty": next_topic["Difficulty"],

    "Estimated Time": next_topic["Estimated_Time"],

    "Resource": resource["Resource_Name"],

    "Resource Type": resource["Resource_Type"],

    "Confidence": confidence,

    "Priority":
        recommendation_priority(confidence),

    "Expected Improvement":
        expected_gain(next_topic["Difficulty"]),

    "Reason":
        generate_reason(
            subject,
            avg_quiz,
            avg_progress*100
        )
})

    recommendations = sorted(
        recommendations,
        key=lambda x: x["Confidence"],
        reverse=True
    )

    recommendations = recommendations[:3]

    learning_health = calculate_learning_health(student_id)

    output = {

        "Student":

        student["Student_Name"],

        "Course":

        student["Course"],

        "Semester":

        student["Semester"],

        "Goal":

        student["Learning_Goal"],

        "Learning Health":

        learning_health,

        "Motivation":

        motivational_message(
            learning_health
        ),

        "Recommendations":

        recommendations
    }

    return output

**3. MINOR TESTS**

In [162]:
history = pd.read_csv("lms_dataset/learning_history.csv")

In [163]:
print(history.shape)

(50000, 11)

In [164]:
history.head()

,Student_ID,Subject,Topic,Quiz_Score,Topics_Completed,Time_Spent_Per_Topic,Attempts,Learning_Progress,Previous_Recommendation,Completion_Status,Study_Date
0,S08871,Manufacturing Processes,Introduction to Casting,82.2,1,15,1,0.01,None (Initial Assessment),Completed,2025-04-19
1,S09059,Accountancy,Introduction to Journal & Ledger,84.6,1,36,1,0.01,None (Initial Assessment),Completed,2023-12-16
2,S01569,Transportation Engineering,Introduction to Highway Design,71.5,1,20,1,0.02,None (Initial Assessment),In Progress,2024-06-09
3,S07799,Social Science,Introduction to History Foundations,63.1,1,15,2,0.02,None (Initial Assessment),In Progress,2024-05-28
4,S04724,Software Engineering,Introduction to SDLC Models,51.5,1,11,3,0.01,None (Initial Assessment),In Progress,2024-07-23

In [165]:
print(history["Student_ID"].head(10).tolist())

['S08871', 'S09059', 'S01569', 'S07799', 'S04724', 'S06812', 'S04740', 'S00778', 'S08380', 'S00852']

In [166]:
print("Occurrences of S00001:")
print((history["Student_ID"] == "S00001").sum())

Occurrences of S00001:
10

In [167]:
result = generate_learning_path("S00001")

print(result["Learning Health"])

52.0

# **PHASE 5: FINAL COMPOSITION**

**1. VERIFICATION OF COMPOSITES**

In [168]:
def calculate_learning_streak(student_id):

    history_df = get_learning_history(student_id)

    if history_df.empty:
        return 0

    study_dates = sorted(set(pd.to_datetime(history_df["Study_Date"]).dt.date))

    streak = 1
    for i in range(len(study_dates) - 1, 0, -1):
        gap_days = (study_dates[i] - study_dates[i - 1]).days
        if gap_days == 1:
            streak += 1
        else:
            break

    return streak

In [169]:

def daily_study_target_from_health(health):

    if health >= 90:
        return 20
    elif health >= 75:
        return 30
    elif health >= 60:
        return 45
    else:
        return 60


def calculate_daily_study_target(student_id):

    health = calculate_learning_health(student_id)
    return daily_study_target_from_health(health)


def risk_badge_from_health(health):

    if health >= 75:
        return "Low"
    elif health >= 50:
        return "Moderate"
    else:
        return "High"


def calculate_risk_badge(student_id):

    health = calculate_learning_health(student_id)
    return risk_badge_from_health(health)

In [170]:


def recommendation_confidence_v2(quiz, progress, rating, attempts=1):

    quiz = 0 if pd.isna(quiz) else quiz
    progress = 0 if pd.isna(progress) else progress
    rating = 0 if pd.isna(rating) else rating
    attempts = 1 if pd.isna(attempts) else attempts

    quiz_norm = float(np.clip(quiz, 0, 100))
    progress_norm = float(np.clip(progress * 100, 0, 100))
    rating_norm = float(np.clip(rating * 20, 0, 100))
    attempt_penalty = float(np.clip((attempts - 1) * 5, 0, 20))

    confidence = (
        0.30 * quiz_norm
        + 0.35 * progress_norm
        + 0.25 * rating_norm
        + 0.10 * (100 - attempt_penalty)
    )

    return round(float(np.clip(confidence, 0, 100)), 2)

In [171]:


def generate_reason_v2(subject, quiz_score, progress, attempts, difficulty):

    reasons = generate_reason(subject, quiz_score, progress)  # reuse original logic

    if attempts is not None and not pd.isna(attempts):
        if attempts >= 4:
            reasons.append(
                "Multiple attempts on recent topics suggest extra practice "
                "will help before advancing further."
            )
        elif attempts <= 1:
            reasons.append(
                "Recent topics were cleared in a single attempt - a good "
                "sign for tackling this next."
            )

    has_quiz = quiz_score is not None and not pd.isna(quiz_score)
    if difficulty == "Advanced" and has_quiz and quiz_score >= 80:
        reasons.append("Strong recent scores make this a good time to attempt an advanced topic.")
    elif difficulty == "Beginner" and has_quiz and quiz_score < 60:
        reasons.append("Starting with a beginner-level topic will help rebuild confidence.")

    return reasons

In [172]:

def estimate_completion_time(student_id, subject):

    subject_topics = get_topics(subject)
    total_topics = subject_topics["Topic"].nunique()

    if total_topics == 0:
        return None

    history_df = get_learning_history(student_id)
    subject_history = history_df[history_df["Subject"] == subject]

    if subject_history.empty:
        return None

    completed = subject_history["Topics_Completed"].max()
    remaining = max(total_topics - completed, 0)

    if remaining == 0:
        return 0

    active_days = subject_history["Study_Date"].nunique()
    sessions = len(subject_history)
    pace = (sessions / active_days) if active_days > 0 else 1
    pace = pace if pace > 0 else 1

    estimated_days = int(np.ceil(remaining / pace))
    return estimated_days

**2. PERSONA IDENTIFICATION**

In [173]:


def determine_learning_persona(student_id):

    history_df = get_learning_history(student_id)

    if history_df.empty:
        return "New Learner"

    avg_quiz = history_df["Quiz_Score"].fillna(0).mean()
    avg_attempts = history_df["Attempts"].fillna(1).mean()
    n_subjects = history_df["Subject"].nunique()
    completion_rate = (history_df["Completion_Status"] == "Completed").mean() * 100
    streak = calculate_learning_streak(student_id)

    if avg_quiz >= 85 and completion_rate >= 60:
        return "High Performer"
    elif avg_attempts <= 1.5 and avg_quiz >= 75:
        return "Fast Learner"
    elif avg_attempts >= 3:
        return "Revision Seeker"
    elif streak >= 5:
        return "Consistent Learner"
    elif n_subjects >= 4:
        return "Explorer"
    else:
        return "Developing Learner"

In [174]:

def calculate_alie_score(student_id):

    history_df = get_learning_history(student_id)

    if history_df.empty:
        return {"ALIE_Score": 0.0, "Breakdown": {}}

    performance = history_df["Quiz_Score"].fillna(0).mean()
    progress = history_df["Learning_Progress"].fillna(0).max() * 100
    completion_rate = (history_df["Completion_Status"] == "Completed").mean() * 100
    engagement = min((history_df["Topics_Completed"].fillna(0).max() / 10) * 100, 100)
    consistency = min(calculate_learning_streak(student_id) * 10, 100)

    breakdown = {
        "Performance": round(performance, 1),
        "Progress": round(progress, 1),
        "Completion": round(completion_rate, 1),
        "Engagement": round(engagement, 1),
        "Consistency": round(consistency, 1),
    }

    alie_score = (
        performance * 0.30
        + progress * 0.25
        + completion_rate * 0.15
        + engagement * 0.15
        + consistency * 0.15
    )

    return {
        "ALIE_Score": round(min(alie_score, 100), 1),
        "Breakdown": breakdown,
    }

In [175]:

def calculate_achievement_badges(student_id):

    history_df = get_learning_history(student_id)

    if history_df.empty:
        return []

    badges = []

    streak = calculate_learning_streak(student_id)
    if streak >= 7:
        badges.append("7-Day Streak")
    elif streak >= 3:
        badges.append("3-Day Streak")

    if (history_df["Quiz_Score"] >= 90).any():
        badges.append("Quiz Ace")

    if history_df["Subject"].nunique() >= 4:
        badges.append("Subject Explorer")

    completed_count = (history_df["Completion_Status"] == "Completed").sum()
    if completed_count >= 20:
        badges.append("20 Topics Completed")
    elif completed_count >= 10:
        badges.append("10 Topics Completed")

    if (history_df["Attempts"] == 1).mean() >= 0.5:
        badges.append("First-Try Champion")

    if calculate_learning_health(student_id) >= 90:
        badges.append("Top Performer")

    return badges

**3. ALIE DEPLOYEMENT**

In [176]:


def generate_learning_path_v2(student_id):

    base = generate_learning_path(student_id)

    if isinstance(base, str):
        return base

    health = base["Learning Health"]
    history_df = get_learning_history(student_id)

    enhanced_recommendations = []
    for rec in base["Recommendations"]:
        subject_history = history_df[history_df["Subject"] == rec["Subject"]]
        avg_quiz = subject_history["Quiz_Score"].mean() if not subject_history.empty else None
        avg_progress = subject_history["Learning_Progress"].mean() if not subject_history.empty else None
        avg_attempts = subject_history["Attempts"].mean() if not subject_history.empty else 1

        resource = best_resource(rec["Next Topic"])
        rating = resource["Rating"] if resource is not None else 0

        rec_v2 = dict(rec)
        rec_v2["Confidence_v2"] = recommendation_confidence_v2(
            avg_quiz, avg_progress, rating, avg_attempts
        )
        rec_v2["Reason_v2"] = generate_reason_v2(
            rec["Subject"],
            avg_quiz,
            (avg_progress * 100) if avg_progress is not None else None,
            avg_attempts,
            rec["Difficulty"],
        )
        rec_v2["Estimated_Completion_Days"] = estimate_completion_time(student_id, rec["Subject"])

        enhanced_recommendations.append(rec_v2)

    alie = calculate_alie_score(student_id)

    enhanced_output = dict(base)
    enhanced_output["Recommendations"] = enhanced_recommendations
    enhanced_output["Learning_Streak"] = calculate_learning_streak(student_id)
    enhanced_output["Daily_Study_Target_Minutes"] = daily_study_target_from_health(health)
    enhanced_output["Risk_Badge"] = risk_badge_from_health(health)
    enhanced_output["Learning_Persona"] = determine_learning_persona(student_id)
    enhanced_output["Achievement_Badges"] = calculate_achievement_badges(student_id)
    enhanced_output["ALIE_Score"] = alie["ALIE_Score"]
    enhanced_output["ALIE_Score_Breakdown"] = alie["Breakdown"]

    return enhanced_output

# **FINAL TESTING**

**TEST 1: CHECKING THE DICTIONARIES**

In [177]:
generate_learning_path("S00001")

{'Student': 'Allison Hill',
 'Course': 'MSc',
 'Semester': 'Semester 3',
 'Goal': 'Certification Prep',
 'Learning Health': np.float64(52.0),
 'Motivation': "Don't worry. Every expert started as a beginner. Let's strengthen the fundamentals step by step.",
 'Recommendations': [{'Subject': 'Advanced Chemistry',
   'Current Topic': 'Quick Revision of Spectroscopy',
   'Next Topic': 'Essential Terminology of Spectroscopy',
   'Difficulty': 'Beginner',
   'Estimated Time': np.int64(19),
   'Resource': 'Worksheet: Essential Terminology of Spectroscopy',
   'Resource Type': 'Practice Problems',
   'Confidence': np.float64(50.23),
   'Priority': 'Low',
   'Expected Improvement': 12,
   'Reason': ['Moderate understanding; strengthening this topic will improve consistency.',
    'Learning progress is still developing.']},
  {'Subject': 'Advanced Mathematics',
   'Current Topic': 'Fundamentals of Real Analysis',
   'Next Topic': 'Quick Revision of Real Analysis',
   'Difficulty': 'Beginner',
   'Estimated Time': np.int64(18),
   'Resource': 'Applied Case Analysis: Quick Revision of Real Analysis',
   'Resource Type': 'Case Study',
   'Confidence': np.float64(48.18),
   'Priority': 'Low',
   'Expected Improvement': 12,
   'Reason': ['Moderate understanding; strengthening this topic will improve consistency.',
    'Learning progress is still developing.']},
  {'Subject': 'Advanced Biology',
   'Current Topic': 'Essential Terminology of Molecular Genetics',
   'Next Topic': 'Molecular Genetics: Core Concepts',
   'Difficulty': 'Intermediate',
   'Estimated Time': np.int64(56),
   'Resource': 'Interactive Simulation: Molecular Genetics: Core Concepts',
   'Resource Type': 'Interactive Lab',
   'Confidence': np.float64(47.81),
   'Priority': 'Low',
   'Expected Improvement': 8,
   'Reason': ['Moderate understanding; strengthening this topic will improve consistency.',
    'Learning progress is still developing.']}]}

**TEST 2: ALIE'S TERMINAL OUTPUT**

In [178]:
result = generate_learning_path("S00001")

print("="*60)
print("STUDENT PROFILE")
print("="*60)

print(f"Student : {result['Student']}")
print(f"Course : {result['Course']}")
print(f"Semester : {result['Semester']}")
print(f"Goal : {result['Goal']}")

print()
print(f"Learning Health : {result['Learning Health']}%")
print()
print(result["Motivation"])

print()
print("="*60)
print("TOP 3 RECOMMENDATIONS")
print("="*60)

for i, rec in enumerate(result["Recommendations"], 1):

    print(f"\nRecommendation {i}")
    print("-"*40)

    print(f"Subject : {rec['Subject']}")
    print(f"Current Topic : {rec['Current Topic']}")
    print(f"Next Topic : {rec['Next Topic']}")
    print(f"Difficulty : {rec['Difficulty']}")
    print(f"Estimated Time : {rec['Estimated Time']} mins")

    print(f"Resource : {rec['Resource']}")
    print(f"Resource Type : {rec['Resource Type']}")

    print(f"Confidence : {rec['Confidence']}%")
    print(f"Priority : {rec['Priority']}")

    print(f"Expected Improvement : +{rec['Expected Improvement']} Health")

    print("Reason:")

    for reason in rec["Reason"]:
        print(f"   • {reason}")

    print()
    print("="*60)
    print("END OF AI REPORT")
    print("="*60)

============================================================
STUDENT PROFILE
============================================================
Student : Allison Hill
Course : MSc
Semester : Semester 3
Goal : Certification Prep

Learning Health : 52.0%

Don't worry. Every expert started as a beginner. Let's strengthen the fundamentals step by step.

============================================================
TOP 3 RECOMMENDATIONS
============================================================

Recommendation 1
----------------------------------------
Subject : Advanced Chemistry
Current Topic : Quick Revision of Spectroscopy
Next Topic : Essential Terminology of Spectroscopy
Difficulty : Beginner
Estimated Time : 19 mins
Resource : Worksheet: Essential Terminology of Spectroscopy
Resource Type : Practice Problems
Confidence : 50.23%
Priority : Low
Expected Improvement : +12 Health
Reason:
   • Moderate understanding; strengthening this topic will improve consistency.
   • Learning progress is still developing.

============================================================
END OF AI REPORT
============================================================

Recommendation 2
----------------------------------------
Subject : Advanced Mathematics
Current Topic : Fundamentals of Real Analysis
Next Topic : Quick Revision of Real Analysis
Difficulty : Beginner
Estimated Time : 18 mins
Resource : Applied Case Analysis: Quick Revision of Real Analysis
Resource Type : Case Study
Confidence : 48.18%
Priority : Low
Expected Improvement : +12 Health
Reason:
   • Moderate understanding; strengthening this topic will improve consistency.
   • Learning progress is still developing.

============================================================
END OF AI REPORT
============================================================

Recommendation 3
----------------------------------------
Subject : Advanced Biology
Current Topic : Essential Terminology of Molecular Genetics
Next Topic : Molecular Genetics: Core Concepts
Difficulty : Intermediate
Estimated Time : 56 mins
Resource : Interactive Simulation: Molecular Genetics: Core Concepts
Resource Type : Interactive Lab
Confidence : 47.81%
Priority : Low
Expected Improvement : +8 Health
Reason:
   • Moderate understanding; strengthening this topic will improve consistency.
   • Learning progress is still developing.

============================================================
END OF AI REPORT
============================================================

# **WEB APP LOCATION**

URL Adresss: https://alie-techrush.lovable.app/

The website was generated by outpouring both notebooks:

01_ALIE_Model_Development.ipynb (Notebook 1)

02_ALIE_Recommendation_Engine.ipynb (Notebook 2)

Lovable AI primary used HTML, CSS, and took source from the dataset both OULAD and the self created to design the path recommendator website as you can access from above.